# ---------------------------------
# Finds third party pthreads VCE2 (largely for Fieldtrip)
# Adds library to target
# Adds include path
# ---------------------------------

IF(WIN32)
	SET(PTHREAD_LIB "PTHREAD_LIB-NOTFOUND")
	FIND_LIBRARY(PTHREAD_LIB pthreadVCE2 PATHS ${OV_CUSTOM_DEPENDENCIES_PATH}/pthreads/lib/ NO_DEFAULT_PATH)
	FIND_LIBRARY(PTHREAD_LIB pthreadVCE2 PATHS ${OV_CUSTOM_DEPENDENCIES_PATH}/pthreads/lib/)	
	
	INCLUDE("OvSetWindowsSDKPath")
	SET(WS232_LIB "WS232_LIB-NOTFOUND")
	FIND_LIBRARY(WS232_LIB ws2_32 ${OV_MS_SDK_PATH}/lib NO_DEFAULT_PATH)
	FIND_LIBRARY(WS232_LIB ws2_32 ${OV_MS_SDK_PATH}/lib)
	
	IF(PTHREAD_LIB AND WS232_LIB)
		MESSAGE(STATUS "  Found PThreads VCE2")
		INCLUDE_DIRECTORIES(${OV_CUSTOM_DEPENDENCIES_PATH}/pthreads/include)		
		TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${WS232_LIB})
		TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${PTHREAD_LIB})
		ADD_DEFINITIONS(-DTARGET_HAS_PThreadsVCE2)	
	ELSE(PTHREAD_LIB AND WS232_LIB)
		MESSAGE(STATUS "  FAILED to find PThreads VCE2")
	ENDIF(PTHREAD_LIB AND WS232_LIB)

	IF(PTHREAD_LIB)
		MESSAGE(STATUS "    [  OK  ] Third party lib ${PTHREAD_LIB}")
	ELSE(PTHREAD_LIB)
		MESSAGE(STATUS "    [FAILED] Third party lib ${PTHREAD_LIB}")
	ENDIF(PTHREAD_LIB)
	
	IF(WS232_LIB)
		MESSAGE(STATUS "    [  OK  ] Third party lib ${WS232_LIB}")
	ELSE(WS232_LIB)
		MESSAGE(STATUS "    [FAILED] Third party lib ${WS232_LIB}")
	ENDIF(WS232_LIB)
	
ENDIF(WIN32)
