# ---------------------------------
# Finds module XML
# Adds library to target
# Adds include path
# ---------------------------------
OPTION(DYNAMIC_LINK_OPENVIBE_MODULE_XML "Dynamically link OpenViBE module XML" ON)

IF(DYNAMIC_LINK_OPENVIBE_MODULE_XML)
	SET(OPENVIBE_MODULE_XML_LINKING "")
ELSE(DYNAMIC_LINK_OPENVIBE_MODULE_XML)
	SET(OPENVIBE_MODULE_XML_LINKING "-static")
ENDIF(DYNAMIC_LINK_OPENVIBE_MODULE_XML)


set(SRC_DIR ${OV_BASE_DIR}/modules/xml/include)

FIND_PATH(PATH_OPENVIBE_MODULES_XML xml/defines.h PATHS ${SRC_DIR}  NO_DEFAULT_PATH)
IF(PATH_OPENVIBE_MODULES_XML)
	MESSAGE(STATUS "  Found OpenViBE module XML...")
	INCLUDE_DIRECTORIES(${PATH_OPENVIBE_MODULES_XML}/)

	TARGET_LINK_LIBRARIES(${PROJECT_NAME} openvibe-module-xml${OPENVIBE_MODULE_XML_LINKING})

	ADD_DEFINITIONS(-DTARGET_HAS_XML)
ELSE(PATH_OPENVIBE_MODULES_XML)
	MESSAGE(STATUS "  FAILED to find OpenViBE module XML...")
ENDIF(PATH_OPENVIBE_MODULES_XML)
