# ---------------------------------
# Finds module XML
# Adds library to target
# Adds include path
# ---------------------------------
OPTION(DYNAMIC_LINK_OPENVIBE_MODULE_XML "Dynamically link OpenViBE module XML" ON)

IF(DYNAMIC_LINK_OPENVIBE_MODULE_XML)
	ADD_DEFINITIONS(-DXML_Shared)
ENDIF(DYNAMIC_LINK_OPENVIBE_MODULE_XML)

IF(DYNAMIC_LINK_OPENVIBE_MODULE_XML)
	SET(OPENVIBE_MODULE_XML_LINKING dynamic)
ELSE(DYNAMIC_LINK_OPENVIBE_MODULE_XML)
	SET(OPENVIBE_MODULE_XML_LINKING static)
ENDIF(DYNAMIC_LINK_OPENVIBE_MODULE_XML)


IF(OV_BRANCH_MODULES_XML)
	set(SRC_DIR ${OV_BASE_DIR}/openvibe-modules/xml/${OV_BRANCH_MODULES_XML})
ELSE(OV_BRANCH_MODULES_XML)
	set(SRC_DIR ${OV_BASE_DIR}/openvibe-modules/xml/${OV_TRUNK})
ENDIF(OV_BRANCH_MODULES_XML)

FIND_PATH(PATH_OPENVIBE_MODULES_XML src/xml/defines.h PATHS ${SRC_DIR})
IF(PATH_OPENVIBE_MODULES_XML)
	MESSAGE(STATUS "  Found OpenViBE module XML...")
	INCLUDE_DIRECTORIES(${PATH_OPENVIBE_MODULES_XML}/src/)

	TARGET_LINK_LIBRARIES(${PROJECT_NAME}-dynamic OpenViBE-module-XML-${OPENVIBE_MODULE_XML_LINKING})

	ADD_DEFINITIONS(-DTARGET_HAS_XML)
ELSE(PATH_OPENVIBE_MODULES_XML)
	MESSAGE(STATUS "  FAILED to find OpenViBE module XML...")
ENDIF(PATH_OPENVIBE_MODULES_XML)
