# ---------------------------------
# Finds OpenViBE
# Adds library to target
# Adds include path
# ---------------------------------
OPTION(DYNAMIC_LINK_OPENVIBE "Dynamically link OpenViBE" ON)

IF(DYNAMIC_LINK_OPENVIBE)
	ADD_DEFINITIONS(-DOV_Shared)
ENDIF(DYNAMIC_LINK_OPENVIBE)

IF(DYNAMIC_LINK_OPENVIBE)
	SET(OPENVIBE_LINKING dynamic)
ELSE(DYNAMIC_LINK_OPENVIBE)
	SET(OPENVIBE_LINKING static)
ENDIF(DYNAMIC_LINK_OPENVIBE)

IF(OV_BRANCH_OPENVIBE)
	set(SRC_DIR $ENV{OpenViBE_base}/openvibe/${OV_BRANCH_OPENVIBE})
ELSE(OV_BRANCH_OPENVIBE)
	set(SRC_DIR $ENV{OpenViBE_base}/openvibe/${OV_TRUNK})
ENDIF(OV_BRANCH_OPENVIBE)

FIND_PATH(PATH_OPENVIBE src/openvibe/ov_all.h PATHS ${SRC_DIR})
IF(PATH_OPENVIBE)
	MESSAGE(STATUS "  Found OpenViBE...")
	INCLUDE_DIRECTORIES(${PATH_OPENVIBE}/src/)

	TARGET_LINK_LIBRARIES(${PROJECT_NAME}-dynamic OpenViBE-${OPENVIBE_LINKING})
	
	ADD_DEFINITIONS(-DTARGET_HAS_OpenViBE)
ELSE(PATH_OPENVIBE)
	MESSAGE(STATUS "  FAILED to find OpenViBE...")
ENDIF(PATH_OPENVIBE)


