# ---------------------------------
# Finds module EBML
# Adds library to target
# Adds include path
# ---------------------------------
OPTION(DYNAMIC_LINK_OPENVIBE_MODULE_EBML "Dynamically link OpenViBE module EBML" ON)

IF(DYNAMIC_LINK_OPENVIBE_MODULE_EBML)
	ADD_DEFINITIONS(-DEBML_Shared)
ENDIF(DYNAMIC_LINK_OPENVIBE_MODULE_EBML)

IF(DYNAMIC_LINK_OPENVIBE_MODULE_EBML)
	SET(OPENVIBE_MODULE_EBML_LINKING dynamic)
ELSE(DYNAMIC_LINK_OPENVIBE_MODULE_EBML)
	SET(OPENVIBE_MODULE_EBML_LINKING static)
ENDIF(DYNAMIC_LINK_OPENVIBE_MODULE_EBML)

IF(OV_BRANCH_MODULES_EBML)
	set(SRC_DIR $ENV{OpenViBE_base}/openvibe-modules/ebml/${OV_BRANCH_MODULES_EBML})
ELSE(OV_BRANCH_MODULES_EBML)
	set(SRC_DIR $ENV{OpenViBE_base}/openvibe-modules/ebml/${OV_TRUNK})
ENDIF(OV_BRANCH_MODULES_EBML)

FIND_PATH(PATH_OPENVIBE_MODULES_EBML src/ebml/defines.h PATHS ${SRC_DIR})
IF(PATH_OPENVIBE_MODULES_EBML)
	MESSAGE(STATUS "  Found OpenViBE module EBML...")
	INCLUDE_DIRECTORIES(${PATH_OPENVIBE_MODULES_EBML}/src/)

	TARGET_LINK_LIBRARIES(${PROJECT_NAME}-dynamic OpenViBE-module-EBML-${OPENVIBE_MODULE_EBML_LINKING})

	ADD_DEFINITIONS(-DTARGET_HAS_EBML)
ELSE(PATH_OPENVIBE_MODULES_EBML)
	MESSAGE(STATUS "  FAILED to find OpenViBE module EBML...")
ENDIF(PATH_OPENVIBE_MODULES_EBML)
