
IF(NOT OV_MS_SDK_PATH)	
	GET_FILENAME_COMPONENT(OV_MS_SDK_PATH "[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Win32SDK\\Directories;Install Dir]" ABSOLUTE CACHE)
ENDIF(NOT OV_MS_SDK_PATH)	

IF(NOT OV_MS_SDK_PATH)
	GET_FILENAME_COMPONENT(OV_MS_SDK_PATH "[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\MicrosoftSDK\\Directories;Install Dir]" ABSOLUTE CACHE)	
ENDIF(NOT OV_MS_SDK_PATH)
	
IF(NOT OV_MS_SDK_PATH)
	GET_FILENAME_COMPONENT(OV_MS_SDK_PATH "[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Microsoft SDKs\\Windows;CurrentInstallFolder]" ABSOLUTE CACHE)
ENDIF(NOT OV_MS_SDK_PATH)

IF(NOT OV_MS_SDK_PATH)
	MESSAGE(STATUS "Could not find Microsoft Windows SDK")
ENDIF(NOT OV_MS_SDK_PATH)

