# This file specifies the test which should be executed

# The file should be placed in the binary directory ${CTEST_BINARY_DIRECTORY}.

#Each test consists of:

#    The unique name of the test ( eg.: testname1 )
#    The full path to the executable of the test ( eg.: "$ENV{HOME}/bin/TEST_EXECUTABLE_1.sh" )
#    A List of arguments to the executable ( eg.: "ARGUMENT_1" "ARGUMENT_2" etc. ) 


# basic test (just for sample) check that binary directory is readable 
#ADD_TEST(LS_BINARY_PATH "ls" "-all")
#ADD_TEST(PWD_BINARY_PATH "pwd")

## -- Other Tests : Place a file named DartTestfile.txt in path with tests.


SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-plugins/acquisition/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-plugins/turbofieldtrip/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-plugins/tools/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-plugins/vrpn/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-plugins/stimulation/branches/wip-emaby/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-plugins/stimulation/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-plugins/feature-extraction/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-plugins/classification-gpl/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-plugins/signal-processing/branches/wip-emaby/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-plugins/signal-processing/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-plugins/simple-visualisation/branches/wip-lbonnet-p300/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-plugins/simple-visualisation/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-plugins/file-io/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-plugins/samples/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-plugins/examples/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-plugins/classification/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-plugins/stream-codecs/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-plugins/python/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-plugins/streaming/branches/wip-emaby/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-plugins/streaming/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-plugins/signal-processing-gpl/branches/wip-emaby/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-plugins/signal-processing-gpl/branches/wip-acellard-ARFeatures/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-plugins/signal-processing-gpl/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-plugins/matlab/branches/wip-lbonnet-matlabdll/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-plugins/matlab/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-applications/id-generator/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-applications/external-stimulation-connection-example/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-applications/designer/tags/wip-omk4/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-applications/designer/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-applications/ssvep-demo/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-applications/skeleton-generator/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-applications/vr-demo/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-applications/vrpn-simulator/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-applications/plugin-inspector/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-applications/acquisition-server/branches/wip-lbonnet-micromed/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-applications/acquisition-server/branches/wip-lbonnet-gtec/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-applications/acquisition-server/branches/wip-emaby/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-applications/acquisition-server/branches/wip-jfruitet/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-applications/acquisition-server/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-documentation/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe/tags/wip-omk4/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-toolkit/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-scenarios/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-plugins/acquisition/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-plugins/turbofieldtrip/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-plugins/tools/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-plugins/vrpn/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-plugins/stimulation/branches/wip-emaby/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-plugins/stimulation/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-plugins/feature-extraction/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-plugins/classification-gpl/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-plugins/signal-processing/branches/wip-emaby/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-plugins/signal-processing/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-plugins/simple-visualisation/branches/wip-lbonnet-p300/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-plugins/simple-visualisation/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-plugins/file-io/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-plugins/samples/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-plugins/examples/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-plugins/classification/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-plugins/stream-codecs/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-plugins/python/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-plugins/streaming/branches/wip-emaby/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-plugins/streaming/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-plugins/signal-processing-gpl/branches/wip-emaby/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-plugins/signal-processing-gpl/branches/wip-acellard-ARFeatures/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-plugins/signal-processing-gpl/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-plugins/matlab/branches/wip-lbonnet-matlabdll/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-plugins/matlab/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-applications/id-generator/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-applications/external-stimulation-connection-example/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-applications/designer/tags/wip-omk4/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-applications/designer/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-applications/ssvep-demo/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-applications/skeleton-generator/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-applications/vr-demo/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-applications/vrpn-simulator/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-applications/plugin-inspector/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-applications/acquisition-server/branches/wip-lbonnet-micromed/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-applications/acquisition-server/branches/wip-lbonnet-gtec/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-applications/acquisition-server/branches/wip-emaby/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-applications/acquisition-server/branches/wip-jfruitet/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-applications/acquisition-server/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-documentation/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe/tags/wip-omk4/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-toolkit/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-scenarios/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-kernel-omk/tags/wip-omk4/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-kernel-omk/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-modules/xml/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-modules/automaton/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-modules/stream/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-modules/ebml/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-modules/socket/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-modules/fs/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/openvibe-modules/system/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/test/trunk/scripts/software/tmp/vrpn/java_vrpn/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-kernel-omk/tags/wip-omk4/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-kernel-omk/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-modules/xml/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-modules/automaton/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-modules/stream/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-modules/ebml/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-modules/socket/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-modules/fs/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/openvibe-modules/system/trunc/test")
SUBDIRS("${CTEST_SOURCE_DIRECTORY}/scripts/software/tmp/vrpn/java_vrpn/test")




 
