#!/bin/bash

if [ ! -e linux-init_env_command ]; then
	echo You have to configure your \`linux-init_env_command\` file.
	echo \`linux-init_env_command-skeleton\` is a good file to start with...
	exit
fi

source linux-init_env_command

saved_directory=`pwd`

mkdir ../local-tmp 2> /dev/null
for sub_directory in `find cmake -type d -printf "%P\n" | sort`; do
	mkdir "../local-tmp/$sub_directory" 2> /dev/null
	cd "../local-tmp/$sub_directory" 2> /dev/null
	cmake "$saved_directory/cmake/$sub_directory"
	make -j 2
	cd "$saved_directory"
done
