#!/bin/bash

########################################################################################################################
## GLOBAL

## this variable sets the default branch for everything
# OpenViBE_default_branch=

########################################################################################################################
## GENERAL

## these variables set each project branch
# OpenViBE_branch=
# OpenViBE_kernel_branch=
# OpenViBE_toolkit_branch=

########################################################################################################################
## MODULES

## these variables set each module branch
# OpenViBE_module_automaton_branch=
# OpenViBE_module_ebml_branch=
# OpenViBE_module_fs_branch=
# OpenViBE_module_socket_branch=
# OpenViBE_module_stream_branch=
# OpenViBE_module_system_branch=
# OpenViBE_module_xml_branch=

########################################################################################################################
## APPLICATIONS

## these variables set each application branch
# OpenViBE_application_acquisition_server_branch=
# OpenViBE_application_designer_branch=
# OpenViBE_application_id_generator_branch=

########################################################################################################################
## PLUGINS

## these variables set each plugin package branch
# OpenViBE_plugin_acquisition_branch=
# OpenViBE_plugin_classification_branch=
# OpenViBE_plugin_classification_gpl_branch=
# OpenViBE_plugin_feature_extraction_branch=
# OpenViBE_plugin_file_io_branch=
# OpenViBE_plugin_samples_branch=
# OpenViBE_plugin_signal_processing_branch=
# OpenViBE_plugin_signal_processing_gpl_branch=
# OpenViBE_plugin_simple_visualisation_branch=
# OpenViBE_plugin_stimulation_branch=
# OpenViBE_plugin_tools_branch=

########################################################################################################################

OpenViBE_base=`pwd`/..

########################################################################################################################

if [ "$OpenViBE_default_branch" == "" ]; then
	OpenViBE_default_branch=trunc
fi

########################################################################################################################

if [ "$OpenViBE_branch" == "" ]; then
	OpenViBE_branch=$OpenViBE_default_branch
fi
if [ "$OpenViBE_kernel_branch" == "" ]; then
	OpenViBE_kernel_branch=$OpenViBE_default_branch
fi
if [ "$OpenViBE_toolkit_branch" == "" ]; then
	OpenViBE_toolkit_branch=$OpenViBE_default_branch
fi

########################################################################################################################

export OpenViBE=$OpenViBE_base/openvibe/$OpenViBE_branch
export OpenViBE_kernel=$OpenViBE_base/openvibe-kernel-omk/$OpenViBE_kernel_branch
export OpenViBE_toolkit=$OpenViBE_base/openvibe-toolkit/$OpenViBE_toolkit_branch

########################################################################################################################

OpenViBE_modules=$OpenViBE_base/openvibe-modules
OpenViBE_modules_all=`find $OpenViBE_modules -mindepth 1 -maxdepth 1 -type d -printf "%P\n" | grep -v \.svn | sort`
OpenViBE_modules_build_order=
for v in $OpenViBE_modules_all; do
	vv=`echo $v | sed 's/\-/_/g'`
	eval 'v_branch=$OpenViBE_module_'$vv'_branch'
	if [ "$v_branch" == "" ]; then
		eval 'OpenViBE_module_'$vv'_branch=$OpenViBE_default_branch'
	fi
	eval 'export OpenViBE_module_'$vv'=$OpenViBE_modules/'$v'/$OpenViBE_module_'$vv'_branch'
	eval 'export OpenViBE_modules_build_order=`echo -e $OpenViBE_modules_build_order"\n"$OpenViBE_module_'$vv'"\n"`'
done

########################################################################################################################

OpenViBE_plugins=$OpenViBE_base/openvibe-plugins
OpenViBE_plugins_all=`find $OpenViBE_plugins -mindepth 1 -maxdepth 1 -type d -printf "%P\n" | grep -v \.svn | sort`
OpenViBE_plugins_build_order=
for v in $OpenViBE_plugins_all; do
	vv=`echo $v | sed 's/\-/_/g'`
	eval 'v_branch=$OpenViBE_plugin_'$vv'_branch'
	if [ "$v_branch" == "" ]; then
		eval 'OpenViBE_plugin_'$vv'_branch=$OpenViBE_default_branch'
	fi
	eval 'export OpenViBE_plugin_'$vv'=$OpenViBE_plugins/'$v'/$OpenViBE_plugin_'$vv'_branch'
	eval 'export OpenViBE_plugins_build_order=`echo -e $OpenViBE_plugins_build_order"\n"$OpenViBE_plugin_'$vv'"\n"`'
done

########################################################################################################################

OpenViBE_applications=$OpenViBE_base/openvibe-applications
OpenViBE_applications_all=`find $OpenViBE_applications -mindepth 1 -maxdepth 1 -type d -printf "%P\n" | grep -v \.svn | sort`
OpenViBE_applications_build_order=
for v in $OpenViBE_applications_all; do
	vv=`echo $v | sed 's/\-/_/g'`
	eval 'v_branch=$OpenViBE_application_'$vv'_branch'
	if [ "$v_branch" == "" ]; then
		eval 'OpenViBE_application_'$vv'_branch=$OpenViBE_default_branch'
	fi
	eval 'export OpenViBE_application_'$vv'=$OpenViBE_applications/'$v'/$OpenViBE_application_'$vv'_branch'
	eval 'export OpenViBE_applications_build_order=`echo -e $OpenViBE_applications_build_order"\n"$OpenViBE_application_'$vv'"\n"`'
done

########################################################################################################################

OpenViBE_build_order=
OpenViBE_build_order=`echo -e $OpenViBE_build_order"\n"$OpenViBE_module_xml` # this is because module "automaton" depends on module "xml"
OpenViBE_build_order=`echo -e $OpenViBE_build_order"\n"$OpenViBE_module_system` # this is because module "stream" depends on module "system"
OpenViBE_build_order=`echo -e $OpenViBE_build_order"\n"$OpenViBE_modules_build_order`
OpenViBE_build_order=`echo -e $OpenViBE_build_order"\n"$OpenViBE`
OpenViBE_build_order=`echo -e $OpenViBE_build_order"\n"$OpenViBE_kernel`
OpenViBE_build_order=`echo -e $OpenViBE_build_order"\n"$OpenViBE_toolkit`
OpenViBE_build_order=`echo -e $OpenViBE_build_order"\n"$OpenViBE_plugins_build_order`
OpenViBE_build_order=`echo -e $OpenViBE_build_order"\n"$OpenViBE_applications_build_order`
export OpenViBE_build_order

if [ -e ./linux-dependencies ]; then
	source ./linux-dependencies
fi;
