#!/bin/bash

if [ ! -e linux-init_env_command ]; then
	echo You have to configure your \`linux-init_env_command\` file.
	echo \`linux-init_env_command-skeleton\` is a good file to start with...
	exit
fi

source linux-init_env_command

mkdir ../local-tmp
cd ../local-tmp
cmake ..
make clean
cd ..
rm -r local-tmp
