#!/bin/bash

if [ ! -e linux-init_env_command ]; then
	echo You have to configure your \`linux-init_env_command\` file.
	echo \`linux-init_env_command-skeleton\` is a good file to start with...
	exit
fi

source linux-init_env_command

./linux-collect_build

cd ../dist/bin
killall OpenViBE-id-generator-dynamic
# killall OpenViBE-plugin-inspector-dynamic
killall OpenViBE-acquisition-server-dynamic
killall OpenViBE-designer-dynamic
./OpenViBE-id-generator-dynamic
# ./OpenViBE-plugin-inspector-dynamic
./OpenViBE-acquisition-server-dynamic &
./OpenViBE-designer-dynamic &
