#!/bin/bash

if [ ! -e linux-init_env_command ]; then
	echo "You have to configure your \`linux-init_env_command\` file."
	echo "\`linux-init_env_command-skeleton\` is a good file to start with..."
	exit
fi

source linux-init_env_command

cd ../dist/bin

export LC_ALL=C

killall OpenViBE-id-generator-dynamic
killall OpenViBE-plugin-inspector-dynamic
killall OpenViBE-acquisition-server-dynamic
killall OpenViBE-designer-dynamic

#gdb ./OpenViBE-id-generator-dynamic
#gdb ./OpenViBE-plugin-inspector-dynamic
#gdb ./OpenViBE-acquisition-server-dynamic
#gdb ./OpenViBE-designer-dynamic

#./OpenViBE-acquisition-server-dynamic
#./OpenViBE-plugin-inspector-dynamic
./OpenViBE-designer-dynamic
