#!/bin/bash

if [ ! -e linux-init_env_command ]; then
	echo "You have to configure your \`linux-init_env_command\` file."
	echo "\`linux-init_env_command-skeleton\` is a good file to start with..."
	exit
fi

source linux-init_env_command

dirDebug="../local-tmp/linux-Debug"
dirRelease="../local-tmp/linux-Release"

if [ -e "$dirDebug" ]; then
	pushd "$dirDebug" 2> /dev/null
	make clean
	popd 2> /dev/null
fi

if [ -e "$dirRelease" ]; then
	pushd "$dirRelease" 2> /dev/null
	make clean
	popd 2> /dev/null
fi

