#!/bin/bash

if [ ! -e linux-init_env_command ]; then
	echo "You have to configure your \`linux-init_env_command\` file."
	echo "\`linux-init_env_command-skeleton\` is a good file to start with... (I'll copy this file for you)"
	cp linux-init_env_command-skeleton linux-init_env_command
fi

source linux-init_env_command

ov_build_type=Release
if [ "$1" == "--debug" ]; then
	ov_build_type=Debug
	shift
fi

echo ""
echo "_______________________________________________________________________________"
echo ""
		
ov_script_dir="${PWD}"
ov_build_dir="${ov_script_dir}/../local-tmp/linux-${ov_build_type}"
ov_install_dir="${ov_script_dir}/../dist"

mkdir -p "${ov_build_dir}" 2> /dev/null
pushd "${ov_build_dir}" 2> /dev/null

echo ""
echo "Creating makefiles..."
echo ""

cmake ${ov_script_dir}/.. -DCMAKE_BUILD_TYPE=${ov_build_type} -DCMAKE_INSTALL_PREFIX=${ov_install_dir}
if [ $? -eq 0 ]; then
	echo CMake has been called successfully !
else
	exit -1
fi;

echo ""
echo "Building ..."
echo ""

make $1 -j 3 # VERBOSE=1
if [ $? -eq 0 ]; then
	echo Make has been called successfully !
else
	exit -1
fi;

echo ""
echo "Installing files to 'dist' folder, this can take a few seconds - maybe a few minutes..."
echo ""

make install
if [ $? -eq 0 ]; then
	echo Make install has been called successfully !
else
	true # exit -1
fi;

popd 2> /dev/null

echo ""
echo "_______________________________________________________________________________"
echo ""

echo ""
echo "Building process terminated successfully !"
echo ""

echo ""
echo "Install completed !"
echo ""

true
