#!/bin/bash

if [ ! -e linux-init_env_command ]; then
	echo "You have to configure your \`linux-init_env_command\` file."
	echo "\`linux-init_env_command-skeleton\` is a good file to start with..."
	exit
fi

source linux-init_env_command

ov_debugger=
if [ "$1" == "--debug" ]; then
	ov_debugger=gdb
	shift
fi

cd ../dist/bin

export LD_LIBRARY_PATH=../lib:$OpenViBE_dependencies/lib:$LD_LIBRARY_PATH
export LC_ALL=C
#renice 19 $$

killall OpenViBE-id-generator-dynamic
killall OpenViBE-plugin-inspector-dynamic
killall OpenViBE-acquisition-server-dynamic
killall OpenViBE-designer-dynamic

#./OpenViBE-id-generator-dynamic
#./OpenViBE-plugin-inspector-dynamic &

if [ "$ov_debugger" == "" ]; then
	./OpenViBE-acquisition-server-dynamic &
	./OpenViBE-designer-dynamic &
else
	$ov_debugger ./OpenViBE-acquisition-server-dynamic
	$ov_debugger ./OpenViBE-designer-dynamic
fi
