#!/bin/bash

./openvibe-acquisition-server.sh $*
./openvibe-designer.sh $*
./openvibe-id-generator.sh $*
./openvibe-plugin-inspector.sh $*
./openvibe-skeleton-generator.sh $*
./openvibe-vr-demo-tie-fighter.sh $*
./openvibe-vrpn-simulator.sh $*
